### ISSUE TITLE
How to create data in a batch?

### ISSUE THREAD

**Issue by JesusEduardo2028** [PredictionIO/PredictionIO-Ruby-SDK#15]
Im collecting a large number of events every 5 minutes, after that i try to send all of them to prediction io inside each block with create_event mehthod. 
```
client = PredictionIO::EventClient.new(ENV['PIO_ACCESS_KEY'], ENV['PIO_EVENT_SERVER_URL'], Integer(ENV['PIO_THREADS']))
rating_events.each do |event|
    request = client.create_event(
      'rate',
      'user',
      self.user_id, {
        'targetEntityType' => 'item',
        'targetEntityId' => self.song_id,
        'properties' => event_info
      })
end
```
Im getting this error

```
Errno::EMFILE (Too many open files @ rb_sysopen - /Users/jesuseduardomunoz/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/better_errors-2.1.1/lib/better_errors/templates/text.erb):
  better_errors (2.1.1) lib/better_errors/error_page.rb:13:in `read'
  better_errors (2.1.1) lib/better_errors/error_page.rb:13:in `template'
  better_errors (2.1.1) lib/better_errors/error_page.rb:30:in `render'
  better_errors (2.1.1) lib/better_errors/middleware.rb:94:in `show_error_page'
  better_errors (2.1.1) lib/better_errors/middleware.rb:88:in `rescue in protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/jesuseduardomunoz/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/jesuseduardomunoz/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/jesuseduardomunoz/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

```

**Comment by tom-chan** [comment]
https://github.com/PredictionIO/PredictionIO-Ruby-SDK/blob/develop/lib/predictionio/file_exporter.rb

This allows you to create a json file for use with "pio import".

**Comment by JesusEduardo2028** [comment]
Tanks!
